default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: "<%= Settings.database[:username]%>"
  password: "<%= Settings.database[:password]%>"
  host: localhost

development:
  <<: *default
  database: railsapp_development

test:
  <<: *default
  database: railsapp_test

production:
  <<: *default
  database: railsapp

